// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/ChangeDesc.proto

package com_variflight_middleware_gateway_cache

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 变更描述，可以表示一个Message或Message中一个Map的变更元数据
// 如果是用于描述Message,则使用fieldTags, changeTags, fieldChangeMetas来描述这个Message中每个field的是否变化和变化内容，具体见相应的字段描述
type ChangeDesc struct {
	// Message中字段变更类型标记，每两位表示一个字段，按字段number值排序，0b00无变更,0b01新建,0b10更新,0b11删除
	FieldTags []byte `protobuf:"bytes,1,opt,name=fieldTags,proto3" json:"fieldTags,omitempty"`
	// Message中字段变更描述索引，对应到fields中的值，每一位表示一个字段，按字段number值排序，0b0表示该字段无变更描述, 0b1表示该字段有变更
	ChangeTags []byte `protobuf:"bytes,2,opt,name=changeTags,proto3" json:"changeTags,omitempty"`
	// Message中内嵌的Message字段或Map字段的变更描述
	FieldsChangeMetas []*ChangeDesc `protobuf:"bytes,3,rep,name=fieldsChangeMetas,proto3" json:"fieldsChangeMetas,omitempty"`
	// Map字段的变更描述，key为map中的key，value为空，则表示该key已删除，不为空且fieldTags长度为0，则表示该key为新增或值已变更(值类型)
	// 不为空，且fieldTags长度不为0，则表示该key对应的value为message类型的变更描述
	MapInt32             map[int32]*ChangeDesc  `protobuf:"bytes,4,rep,name=map_int32,json=mapInt32,proto3" json:"map_int32,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MapInt64             map[int64]*ChangeDesc  `protobuf:"bytes,5,rep,name=map_int64,json=mapInt64,proto3" json:"map_int64,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MapBool              map[bool]*ChangeDesc   `protobuf:"bytes,6,rep,name=map_bool,json=mapBool,proto3" json:"map_bool,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MapString            map[string]*ChangeDesc `protobuf:"bytes,7,rep,name=map_string,json=mapString,proto3" json:"map_string,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ChangeDesc) Reset()         { *m = ChangeDesc{} }
func (m *ChangeDesc) String() string { return proto.CompactTextString(m) }
func (*ChangeDesc) ProtoMessage()    {}
func (*ChangeDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0e9504baabf8402, []int{0}
}

func (m *ChangeDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeDesc.Unmarshal(m, b)
}
func (m *ChangeDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeDesc.Marshal(b, m, deterministic)
}
func (m *ChangeDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeDesc.Merge(m, src)
}
func (m *ChangeDesc) XXX_Size() int {
	return xxx_messageInfo_ChangeDesc.Size(m)
}
func (m *ChangeDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeDesc.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeDesc proto.InternalMessageInfo

func (m *ChangeDesc) GetFieldTags() []byte {
	if m != nil {
		return m.FieldTags
	}
	return nil
}

func (m *ChangeDesc) GetChangeTags() []byte {
	if m != nil {
		return m.ChangeTags
	}
	return nil
}

func (m *ChangeDesc) GetFieldsChangeMetas() []*ChangeDesc {
	if m != nil {
		return m.FieldsChangeMetas
	}
	return nil
}

func (m *ChangeDesc) GetMapInt32() map[int32]*ChangeDesc {
	if m != nil {
		return m.MapInt32
	}
	return nil
}

func (m *ChangeDesc) GetMapInt64() map[int64]*ChangeDesc {
	if m != nil {
		return m.MapInt64
	}
	return nil
}

func (m *ChangeDesc) GetMapBool() map[bool]*ChangeDesc {
	if m != nil {
		return m.MapBool
	}
	return nil
}

func (m *ChangeDesc) GetMapString() map[string]*ChangeDesc {
	if m != nil {
		return m.MapString
	}
	return nil
}

func init() {
	proto.RegisterType((*ChangeDesc)(nil), "com.variflight.middleware.gateway.cache.ChangeDesc")
	proto.RegisterMapType((map[bool]*ChangeDesc)(nil), "com.variflight.middleware.gateway.cache.ChangeDesc.MapBoolEntry")
	proto.RegisterMapType((map[int32]*ChangeDesc)(nil), "com.variflight.middleware.gateway.cache.ChangeDesc.MapInt32Entry")
	proto.RegisterMapType((map[int64]*ChangeDesc)(nil), "com.variflight.middleware.gateway.cache.ChangeDesc.MapInt64Entry")
	proto.RegisterMapType((map[string]*ChangeDesc)(nil), "com.variflight.middleware.gateway.cache.ChangeDesc.MapStringEntry")
}

func init() { proto.RegisterFile("proto/ChangeDesc.proto", fileDescriptor_e0e9504baabf8402) }

var fileDescriptor_e0e9504baabf8402 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xd9, 0xea, 0x7e, 0x3d, 0xa7, 0x68, 0x0e, 0x52, 0x44, 0x64, 0x78, 0x71, 0xa7, 0x08,
	0xdb, 0x18, 0xe2, 0x49, 0xa7, 0x1e, 0x76, 0xd8, 0xa5, 0x7a, 0x13, 0x1c, 0x6f, 0x5d, 0xd6, 0x15,
	0xd3, 0xa6, 0xb6, 0x71, 0x63, 0x7f, 0xb8, 0x77, 0xe9, 0xcb, 0xa0, 0x19, 0x5e, 0xa4, 0xb2, 0x5b,
	0xde, 0x4b, 0xfa, 0xf9, 0x84, 0x6f, 0x1f, 0x81, 0xb3, 0x24, 0x55, 0x5a, 0xdd, 0x3c, 0x2e, 0x31,
	0x0e, 0xc4, 0x93, 0xc8, 0x7c, 0x4e, 0x0d, 0x76, 0xed, 0xab, 0x88, 0xaf, 0x30, 0x0d, 0x17, 0x32,
	0x0c, 0x96, 0x9a, 0x47, 0xe1, 0x7c, 0x2e, 0xc5, 0x1a, 0x53, 0xc1, 0x03, 0xd4, 0x62, 0x8d, 0x1b,
	0xee, 0xa3, 0xbf, 0x14, 0x57, 0xdf, 0x0d, 0x80, 0xe2, 0x6b, 0x76, 0x01, 0xad, 0x45, 0x28, 0xe4,
	0xfc, 0x15, 0x83, 0xcc, 0xad, 0x74, 0x2a, 0xdd, 0xb6, 0x57, 0x34, 0xd8, 0x25, 0x80, 0x4f, 0x67,
	0x69, 0xbb, 0x4a, 0xdb, 0x56, 0x87, 0x21, 0x9c, 0xd2, 0xe1, 0xcc, 0x10, 0x27, 0x42, 0x63, 0xe6,
	0x3a, 0x1d, 0xa7, 0x7b, 0xd8, 0xeb, 0xf3, 0x3f, 0xde, 0x88, 0x17, 0xb7, 0xf1, 0x7e, 0xd3, 0xd8,
	0x3b, 0xb4, 0x22, 0x4c, 0xa6, 0x61, 0xac, 0xfb, 0x3d, 0xf7, 0x80, 0xd0, 0x0f, 0x25, 0xd0, 0x7c,
	0x82, 0xc9, 0x38, 0x67, 0x3c, 0xc7, 0x3a, 0xdd, 0x78, 0xcd, 0x68, 0x5b, 0x5a, 0xfc, 0xe1, 0xc0,
	0xad, 0xfd, 0x97, 0x3f, 0x1c, 0xec, 0xf0, 0x87, 0x03, 0xf6, 0x06, 0xf9, 0x7a, 0x3a, 0x53, 0x4a,
	0xba, 0x75, 0xc2, 0xdf, 0x97, 0xc4, 0x8f, 0x94, 0x92, 0x86, 0xde, 0x88, 0x4c, 0xc5, 0x10, 0x20,
	0x87, 0x67, 0x3a, 0x0d, 0xe3, 0xc0, 0x6d, 0x10, 0x7e, 0x54, 0x12, 0xff, 0x42, 0x10, 0x23, 0xc8,
	0x23, 0x31, 0xf5, 0x79, 0x02, 0x47, 0x3b, 0xd1, 0xb1, 0x13, 0x70, 0x3e, 0xc4, 0x86, 0x66, 0xa5,
	0xe6, 0xe5, 0x4b, 0x36, 0x86, 0xda, 0x0a, 0xe5, 0x97, 0xa0, 0x01, 0x29, 0xf9, 0xe7, 0x0d, 0xe1,
	0xae, 0x7a, 0x5b, 0x29, 0x8c, 0xdb, 0x30, 0x6d, 0xa3, 0xb3, 0x17, 0xa3, 0x82, 0xb6, 0x9d, 0xaf,
	0x2d, 0x6c, 0xee, 0x45, 0xf8, 0x09, 0xc7, 0xbb, 0x89, 0xdb, 0xca, 0xd6, 0x3e, 0x94, 0xb3, 0x3a,
	0xbd, 0x13, 0xfd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x21, 0x87, 0x6c, 0x31, 0x41, 0x04, 0x00,
	0x00,
}
